name: Main


on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: hello_world
    - name: Run build
      run: ./hello_world >> $GITHUB_STEP_SUMMARY
    
