name: Main


on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4.1.7
    - name: Run build
      run: ls -R
    
