name: Rust

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload executable
      uses: actions/upload-artifact@v4.3.3
      with:
        name: hello_world
        path: target/debug/hello_world
        overwrite: true
          
